/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cs203_2.group2.kachingko.dashboard.CreditLimit;

import cs203_2.group2.kachingko.DBConnection;
import javax.swing.*;
import java.awt.*;
import java.util.*;

import cs203_2.group2.kachingko.auth.Session;

/**
 *
 * @author ADMIN
 */
public class CreditUtilization extends javax.swing.JFrame {

    /**
     * Creates new form CreditLimit
     */
    public CreditUtilization() {
        initComponents();
        totalUtilizationPercentage.setEditable(false);
        setTitle("Credit Utilization");
        setSize(460, 680);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creditcard1 = new javax.swing.JLabel();
        creditcard2 = new javax.swing.JLabel();
        creditcard3 = new javax.swing.JLabel();
        balanceTitle = new javax.swing.JLabel();
        limitTitle = new javax.swing.JLabel();
        creditcardBalance1 = new javax.swing.JTextField();
        creditcardLimit1 = new javax.swing.JTextField();
        creditcardBalance2 = new javax.swing.JTextField();
        creditcardLimit2 = new javax.swing.JTextField();
        creditcardBalance3 = new javax.swing.JTextField();
        creditcardLimit3 = new javax.swing.JTextField();
        creditcard4 = new javax.swing.JLabel();
        creditcardBalance4 = new javax.swing.JTextField();
        creditcardLimit4 = new javax.swing.JTextField();
        creditcard5 = new javax.swing.JLabel();
        creditcardLimit5 = new javax.swing.JTextField();
        creditcardBalance5 = new javax.swing.JTextField();
        enterBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        creditcard6 = new javax.swing.JLabel();
        creditcardBalance6 = new javax.swing.JTextField();
        creditcardLimit6 = new javax.swing.JTextField();
        creditcard7 = new javax.swing.JLabel();
        creditcardBalance7 = new javax.swing.JTextField();
        creditcardLimit7 = new javax.swing.JTextField();
        creditcardBalance8 = new javax.swing.JTextField();
        creditcard8 = new javax.swing.JLabel();
        creditcardLimit8 = new javax.swing.JTextField();
        totalUtilizationTitle = new javax.swing.JLabel();
        totalUtilizationPercentage = new javax.swing.JTextField();
        dashboardBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(460, 655));
        getContentPane().setLayout(null);

        creditcard1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        creditcard1.setForeground(new java.awt.Color(55, 74, 34));
        creditcard1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditcard1.setText("CARD 1:");
        creditcard1.setToolTipText("");
        getContentPane().add(creditcard1);
        creditcard1.setBounds(40, 140, 74, 26);

        creditcard2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        creditcard2.setForeground(new java.awt.Color(55, 74, 34));
        creditcard2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditcard2.setText("CARD 2:");
        creditcard2.setToolTipText("");
        getContentPane().add(creditcard2);
        creditcard2.setBounds(40, 190, 76, 26);

        creditcard3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        creditcard3.setForeground(new java.awt.Color(55, 74, 34));
        creditcard3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditcard3.setText("CARD 3:");
        creditcard3.setToolTipText("");
        getContentPane().add(creditcard3);
        creditcard3.setBounds(40, 240, 76, 26);

        balanceTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        balanceTitle.setForeground(new java.awt.Color(96, 108, 56));
        balanceTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balanceTitle.setText("BALANCE");
        balanceTitle.setToolTipText("");
        getContentPane().add(balanceTitle);
        balanceTitle.setBounds(200, 110, 80, 19);

        limitTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        limitTitle.setForeground(new java.awt.Color(96, 108, 56));
        limitTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        limitTitle.setText("LIMIT");
        limitTitle.setToolTipText("");
        getContentPane().add(limitTitle);
        limitTitle.setBounds(340, 110, 50, 20);

        creditcardBalance1.setFont(new java.awt.Font("DM Sans", 0, 12)); // NOI18N
        creditcardBalance1.setForeground(new java.awt.Color(55, 74, 34));
        creditcardBalance1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 74, 34)));
        creditcardBalance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardBalance1ActionPerformed(evt);
            }
        });
        getContentPane().add(creditcardBalance1);
        creditcardBalance1.setBounds(190, 140, 90, 26);

        creditcardLimit1.setFont(new java.awt.Font("DM Sans", 0, 12)); // NOI18N
        creditcardLimit1.setForeground(new java.awt.Color(55, 74, 34));
        creditcardLimit1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 74, 34)));
        creditcardLimit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardLimit1ActionPerformed(evt);
            }
        });
        getContentPane().add(creditcardLimit1);
        creditcardLimit1.setBounds(320, 140, 90, 26);

        creditcardBalance2.setFont(new java.awt.Font("DM Sans", 0, 12)); // NOI18N
        creditcardBalance2.setForeground(new java.awt.Color(55, 74, 34));
        creditcardBalance2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 74, 34)));
        creditcardBalance2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardBalance2ActionPerformed(evt);
            }
        });
        getContentPane().add(creditcardBalance2);
        creditcardBalance2.setBounds(190, 190, 90, 26);

        creditcardLimit2.setFont(new java.awt.Font("DM Sans", 0, 12)); // NOI18N
        creditcardLimit2.setForeground(new java.awt.Color(55, 74, 34));
        creditcardLimit2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 74, 34)));
        creditcardLimit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardLimit2ActionPerformed(evt);
            }
        });
        getContentPane().add(creditcardLimit2);
        creditcardLimit2.setBounds(320, 190, 90, 26);

        creditcardBalance3.setFont(new java.awt.Font("DM Sans", 0, 12)); // NOI18N
        creditcardBalance3.setForeground(new java.awt.Color(55, 74, 34));
        creditcardBalance3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 74, 34)));
        creditcardBalance3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardBalance3ActionPerformed(evt);
            }
        });
        getContentPane().add(creditcardBalance3);
        creditcardBalance3.setBounds(190, 240, 90, 26);

        creditcardLimit3.setFont(new java.awt.Font("DM Sans", 0, 12)); // NOI18N
        creditcardLimit3.setForeground(new java.awt.Color(55, 74, 34));
        creditcardLimit3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 74, 34)));
        creditcardLimit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardLimit3ActionPerformed(evt);
            }
        });
        getContentPane().add(creditcardLimit3);
        creditcardLimit3.setBounds(320, 240, 90, 26);

        creditcard4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        creditcard4.setForeground(new java.awt.Color(55, 74, 34));
        creditcard4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditcard4.setText("CARD 4:");
        creditcard4.setToolTipText("");
        getContentPane().add(creditcard4);
        creditcard4.setBounds(40, 290, 76, 26);

        creditcardBalance4.setFont(new java.awt.Font("DM Sans", 0, 12)); // NOI18N
        creditcardBalance4.setForeground(new java.awt.Color(55, 74, 34));
        creditcardBalance4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 74, 34)));
        creditcardBalance4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardBalance4ActionPerformed(evt);
            }
        });
        getContentPane().add(creditcardBalance4);
        creditcardBalance4.setBounds(190, 290, 90, 26);

        creditcardLimit4.setFont(new java.awt.Font("DM Sans", 0, 12)); // NOI18N
        creditcardLimit4.setForeground(new java.awt.Color(55, 74, 34));
        creditcardLimit4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 74, 34)));
        creditcardLimit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardLimit4ActionPerformed(evt);
            }
        });
        getContentPane().add(creditcardLimit4);
        creditcardLimit4.setBounds(320, 290, 90, 26);

        creditcard5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        creditcard5.setForeground(new java.awt.Color(55, 74, 34));
        creditcard5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditcard5.setText("CARD 5:");
        creditcard5.setToolTipText("");
        getContentPane().add(creditcard5);
        creditcard5.setBounds(40, 340, 76, 26);

        creditcardLimit5.setFont(new java.awt.Font("DM Sans", 0, 12)); // NOI18N
        creditcardLimit5.setForeground(new java.awt.Color(55, 74, 34));
        creditcardLimit5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 74, 34)));
        creditcardLimit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardLimit5ActionPerformed(evt);
            }
        });
        getContentPane().add(creditcardLimit5);
        creditcardLimit5.setBounds(320, 340, 90, 26);

        creditcardBalance5.setFont(new java.awt.Font("DM Sans", 0, 12)); // NOI18N
        creditcardBalance5.setForeground(new java.awt.Color(55, 74, 34));
        creditcardBalance5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 74, 34)));
        creditcardBalance5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardBalance5ActionPerformed(evt);
            }
        });
        getContentPane().add(creditcardBalance5);
        creditcardBalance5.setBounds(190, 340, 90, 26);

        enterBtn.setBackground(new java.awt.Color(55, 74, 34));
        enterBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        enterBtn.setForeground(new java.awt.Color(255, 255, 255));
        enterBtn.setText("ENTER");
        enterBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        enterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterBtnActionPerformed(evt);
            }
        });
        getContentPane().add(enterBtn);
        enterBtn.setBounds(40, 540, 149, 23);

        clearBtn.setBackground(new java.awt.Color(55, 74, 34));
        clearBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn.setText("CLEAR");
        clearBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn);
        clearBtn.setBounds(40, 570, 149, 23);

        creditcard6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        creditcard6.setForeground(new java.awt.Color(55, 74, 34));
        creditcard6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditcard6.setText("CARD 6:");
        creditcard6.setToolTipText("");
        getContentPane().add(creditcard6);
        creditcard6.setBounds(40, 390, 76, 26);

        creditcardBalance6.setFont(new java.awt.Font("DM Sans", 0, 12)); // NOI18N
        creditcardBalance6.setForeground(new java.awt.Color(55, 74, 34));
        creditcardBalance6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 74, 34)));
        creditcardBalance6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardBalance6ActionPerformed(evt);
            }
        });
        getContentPane().add(creditcardBalance6);
        creditcardBalance6.setBounds(190, 390, 90, 26);

        creditcardLimit6.setFont(new java.awt.Font("DM Sans", 0, 12)); // NOI18N
        creditcardLimit6.setForeground(new java.awt.Color(55, 74, 34));
        creditcardLimit6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 74, 34)));
        creditcardLimit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardLimit6ActionPerformed(evt);
            }
        });
        getContentPane().add(creditcardLimit6);
        creditcardLimit6.setBounds(320, 390, 90, 26);

        creditcard7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        creditcard7.setForeground(new java.awt.Color(55, 74, 34));
        creditcard7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditcard7.setText("CARD 7:");
        creditcard7.setToolTipText("");
        getContentPane().add(creditcard7);
        creditcard7.setBounds(40, 440, 76, 26);

        creditcardBalance7.setFont(new java.awt.Font("DM Sans", 0, 12)); // NOI18N
        creditcardBalance7.setForeground(new java.awt.Color(55, 74, 34));
        creditcardBalance7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 74, 34)));
        creditcardBalance7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardBalance7ActionPerformed(evt);
            }
        });
        getContentPane().add(creditcardBalance7);
        creditcardBalance7.setBounds(190, 440, 90, 26);

        creditcardLimit7.setFont(new java.awt.Font("DM Sans", 0, 12)); // NOI18N
        creditcardLimit7.setForeground(new java.awt.Color(55, 74, 34));
        creditcardLimit7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 74, 34)));
        creditcardLimit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardLimit7ActionPerformed(evt);
            }
        });
        getContentPane().add(creditcardLimit7);
        creditcardLimit7.setBounds(320, 440, 90, 26);

        creditcardBalance8.setFont(new java.awt.Font("DM Sans", 0, 12)); // NOI18N
        creditcardBalance8.setForeground(new java.awt.Color(55, 74, 34));
        creditcardBalance8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 74, 34)));
        creditcardBalance8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardBalance8ActionPerformed(evt);
            }
        });
        getContentPane().add(creditcardBalance8);
        creditcardBalance8.setBounds(190, 490, 90, 26);

        creditcard8.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        creditcard8.setForeground(new java.awt.Color(55, 74, 34));
        creditcard8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditcard8.setText("CARD 8:");
        creditcard8.setToolTipText("");
        getContentPane().add(creditcard8);
        creditcard8.setBounds(40, 490, 76, 26);

        creditcardLimit8.setFont(new java.awt.Font("DM Sans", 0, 12)); // NOI18N
        creditcardLimit8.setForeground(new java.awt.Color(55, 74, 34));
        creditcardLimit8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 74, 34)));
        creditcardLimit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardLimit8ActionPerformed(evt);
            }
        });
        getContentPane().add(creditcardLimit8);
        creditcardLimit8.setBounds(320, 490, 90, 26);

        totalUtilizationTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        totalUtilizationTitle.setForeground(new java.awt.Color(55, 74, 34));
        totalUtilizationTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalUtilizationTitle.setText("TOTAL UTILIZATION");
        totalUtilizationTitle.setToolTipText("");
        getContentPane().add(totalUtilizationTitle);
        totalUtilizationTitle.setBounds(200, 540, 180, 19);

        totalUtilizationPercentage.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        totalUtilizationPercentage.setForeground(new java.awt.Color(55, 74, 34));
        totalUtilizationPercentage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 74, 34)));
        totalUtilizationPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalUtilizationPercentageActionPerformed(evt);
            }
        });
        getContentPane().add(totalUtilizationPercentage);
        totalUtilizationPercentage.setBounds(220, 570, 180, 40);

        dashboardBtn.setBackground(new java.awt.Color(96, 108, 56));
        dashboardBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        dashboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        dashboardBtn.setText("BACK TO DASHBOARD");
        dashboardBtn.setActionCommand("RETURN TO DASHBOARD");
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        getContentPane().add(dashboardBtn);
        dashboardBtn.setBounds(40, 600, 149, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cardBG.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 460, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creditcardBalance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardBalance1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardBalance1ActionPerformed

    private void creditcardLimit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardLimit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardLimit1ActionPerformed

    private void creditcardBalance2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardBalance2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardBalance2ActionPerformed

    private void creditcardLimit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardLimit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardLimit2ActionPerformed

    private void creditcardBalance3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardBalance3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardBalance3ActionPerformed

    private void creditcardLimit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardLimit3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardLimit3ActionPerformed

    private void creditcardBalance4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardBalance4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardBalance4ActionPerformed

    private void creditcardLimit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardLimit4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardLimit4ActionPerformed

    private void creditcardLimit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardLimit5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardLimit5ActionPerformed

    private void creditcardBalance5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardBalance5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardBalance5ActionPerformed

    private void enterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterBtnActionPerformed
        double totalBalance = 0;
        double totalLimit = 0;
        int cardsFilled = 0;

// Arrays of credit card balance and limit fields
JTextField[] balanceFields = {
    creditcardBalance1, creditcardBalance2, creditcardBalance3, creditcardBalance4, creditcardBalance5, creditcardBalance6, creditcardBalance7, creditcardBalance8
};
JTextField[] limitFields = {
    creditcardLimit1, creditcardLimit2, creditcardLimit3, creditcardLimit4, creditcardLimit5, creditcardLimit6, creditcardLimit7, creditcardLimit8
};

for (int i = 0; i < balanceFields.length; i++) {
    String balanceText = balanceFields[i].getText().trim();
    String limitText = limitFields[i].getText().trim();

    if (!balanceText.isEmpty() && !limitText.isEmpty()) {
        try {
            double balance = Double.parseDouble(balanceText);
            double limit = Double.parseDouble(limitText);

            if (limit <= 0) {
                JOptionPane.showMessageDialog(this, "Credit card " + (i + 1) + " must have a limit greater than 0.");
                return;
            }

            totalBalance += balance;
            totalLimit += limit;
            cardsFilled++;

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid number in credit card " + (i + 1));
            return;
        }
    }
}
//Needs atleast one credit card balance and limit input to function
if (cardsFilled == 0) {
    JOptionPane.showMessageDialog(this, "Please fill in at least one credit card's balance and limit.");
    return;
}

double utilization = (totalBalance / totalLimit) * 100;
String utilizationText = String.format("%.2f", utilization);

// Display in the utilization field together with it's dedicated color
totalUtilizationPercentage.setText(utilizationText + "%");

if (utilization < 30) {
    totalUtilizationPercentage.setBackground(Color.GREEN);
} else if (utilization < 70) {
    totalUtilizationPercentage.setBackground(Color.YELLOW);
} else {
    totalUtilizationPercentage.setBackground(Color.RED);
}
    }//GEN-LAST:event_enterBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        JTextField[] allFields = {
        creditcardBalance1, creditcardBalance2, creditcardBalance3, creditcardBalance4,
        creditcardBalance5, creditcardBalance6, creditcardBalance7, creditcardBalance8,
        creditcardLimit1, creditcardLimit2, creditcardLimit3, creditcardLimit4,
        creditcardLimit5, creditcardLimit6, creditcardLimit7, creditcardLimit8,
        totalUtilizationPercentage
    };
    
    for (JTextField field : allFields) {
        field.setText("");
    }
    }//GEN-LAST:event_clearBtnActionPerformed

    private void creditcardBalance6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardBalance6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardBalance6ActionPerformed

    private void creditcardLimit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardLimit6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardLimit6ActionPerformed

    private void creditcardBalance7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardBalance7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardBalance7ActionPerformed

    private void creditcardLimit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardLimit7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardLimit7ActionPerformed

    private void creditcardBalance8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardBalance8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardBalance8ActionPerformed

    private void creditcardLimit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardLimit8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardLimit8ActionPerformed

    private void totalUtilizationPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalUtilizationPercentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalUtilizationPercentageActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditUtilization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditUtilization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditUtilization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditUtilization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreditUtilization().setVisible(true);
                
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balanceTitle;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel creditcard1;
    private javax.swing.JLabel creditcard2;
    private javax.swing.JLabel creditcard3;
    private javax.swing.JLabel creditcard4;
    private javax.swing.JLabel creditcard5;
    private javax.swing.JLabel creditcard6;
    private javax.swing.JLabel creditcard7;
    private javax.swing.JLabel creditcard8;
    private javax.swing.JTextField creditcardBalance1;
    private javax.swing.JTextField creditcardBalance2;
    private javax.swing.JTextField creditcardBalance3;
    private javax.swing.JTextField creditcardBalance4;
    private javax.swing.JTextField creditcardBalance5;
    private javax.swing.JTextField creditcardBalance6;
    private javax.swing.JTextField creditcardBalance7;
    private javax.swing.JTextField creditcardBalance8;
    private javax.swing.JTextField creditcardLimit1;
    private javax.swing.JTextField creditcardLimit2;
    private javax.swing.JTextField creditcardLimit3;
    private javax.swing.JTextField creditcardLimit4;
    private javax.swing.JTextField creditcardLimit5;
    private javax.swing.JTextField creditcardLimit6;
    private javax.swing.JTextField creditcardLimit7;
    private javax.swing.JTextField creditcardLimit8;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JButton enterBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel limitTitle;
    private javax.swing.JTextField totalUtilizationPercentage;
    private javax.swing.JLabel totalUtilizationTitle;
    // End of variables declaration//GEN-END:variables
}
