/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cs203_2.group2.kachingko.dashboard.CreditLimit;

import cs203_2.group2.kachingko.DBConnection;
import javax.swing.*;
import java.awt.*;
import java.util.*;

import cs203_2.group2.kachingko.auth.Session;

/**
 *
 * @author ADMIN
 */
public class CreditUtilization extends javax.swing.JFrame {

    /**
     * Creates new form CreditLimit
     */
    public CreditUtilization() {
        initComponents();
        totalUtilizationPercentage.setEditable(false);
        setTitle("Credit Utilization");
        setSize(460, 680);
        setResizable(false);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creditUtilizationHeader = new javax.swing.JLabel();
        creditcard1 = new javax.swing.JLabel();
        creditcard2 = new javax.swing.JLabel();
        creditcard3 = new javax.swing.JLabel();
        balanceTitle = new javax.swing.JLabel();
        limitTitle = new javax.swing.JLabel();
        creditcardBalance1 = new javax.swing.JTextField();
        creditcardLimit1 = new javax.swing.JTextField();
        creditcardBalance2 = new javax.swing.JTextField();
        creditcardLimit2 = new javax.swing.JTextField();
        creditcardBalance3 = new javax.swing.JTextField();
        creditcardLimit3 = new javax.swing.JTextField();
        creditcard4 = new javax.swing.JLabel();
        creditcardBalance4 = new javax.swing.JTextField();
        creditcardLimit4 = new javax.swing.JTextField();
        creditcard5 = new javax.swing.JLabel();
        creditcardLimit5 = new javax.swing.JTextField();
        creditcardBalance5 = new javax.swing.JTextField();
        enterBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        creditcard6 = new javax.swing.JLabel();
        creditcardBalance6 = new javax.swing.JTextField();
        creditcardLimit6 = new javax.swing.JTextField();
        creditcard7 = new javax.swing.JLabel();
        creditcardBalance7 = new javax.swing.JTextField();
        creditcardLimit7 = new javax.swing.JTextField();
        creditcardBalance8 = new javax.swing.JTextField();
        creditcard8 = new javax.swing.JLabel();
        creditcardLimit8 = new javax.swing.JTextField();
        totalUtilizationTitle = new javax.swing.JLabel();
        totalUtilizationPercentage = new javax.swing.JTextField();
        dashboardBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(460, 655));

        creditUtilizationHeader.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        creditUtilizationHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditUtilizationHeader.setText("Credit Limit Utilization");
        creditUtilizationHeader.setToolTipText("");

        creditcard1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        creditcard1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditcard1.setText("Credit Card 1:");
        creditcard1.setToolTipText("");

        creditcard2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        creditcard2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditcard2.setText("Credit Card 2:");
        creditcard2.setToolTipText("");

        creditcard3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        creditcard3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditcard3.setText("Credit Card 3:");
        creditcard3.setToolTipText("");

        balanceTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        balanceTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balanceTitle.setText("Balance");
        balanceTitle.setToolTipText("");

        limitTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        limitTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        limitTitle.setText("Limit");
        limitTitle.setToolTipText("");

        creditcardBalance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardBalance1ActionPerformed(evt);
            }
        });

        creditcardLimit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardLimit1ActionPerformed(evt);
            }
        });

        creditcardBalance2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardBalance2ActionPerformed(evt);
            }
        });

        creditcardLimit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardLimit2ActionPerformed(evt);
            }
        });

        creditcardBalance3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardBalance3ActionPerformed(evt);
            }
        });

        creditcardLimit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardLimit3ActionPerformed(evt);
            }
        });

        creditcard4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        creditcard4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditcard4.setText("Credit Card 4:");
        creditcard4.setToolTipText("");

        creditcardBalance4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardBalance4ActionPerformed(evt);
            }
        });

        creditcardLimit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardLimit4ActionPerformed(evt);
            }
        });

        creditcard5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        creditcard5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditcard5.setText("Credit Card 5:");
        creditcard5.setToolTipText("");

        creditcardLimit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardLimit5ActionPerformed(evt);
            }
        });

        creditcardBalance5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardBalance5ActionPerformed(evt);
            }
        });

        enterBtn.setText("Enter");
        enterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        creditcard6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        creditcard6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditcard6.setText("Credit Card 6:");
        creditcard6.setToolTipText("");

        creditcardBalance6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardBalance6ActionPerformed(evt);
            }
        });

        creditcardLimit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardLimit6ActionPerformed(evt);
            }
        });

        creditcard7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        creditcard7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditcard7.setText("Credit Card 7:");
        creditcard7.setToolTipText("");

        creditcardBalance7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardBalance7ActionPerformed(evt);
            }
        });

        creditcardLimit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardLimit7ActionPerformed(evt);
            }
        });

        creditcardBalance8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardBalance8ActionPerformed(evt);
            }
        });

        creditcard8.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        creditcard8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditcard8.setText("Credit Card 8:");
        creditcard8.setToolTipText("");

        creditcardLimit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardLimit8ActionPerformed(evt);
            }
        });

        totalUtilizationTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        totalUtilizationTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalUtilizationTitle.setText("Total Utilization");
        totalUtilizationTitle.setToolTipText("");

        totalUtilizationPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalUtilizationPercentageActionPerformed(evt);
            }
        });

        dashboardBtn.setText("Return to Dashboard");
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(creditcard2)
                            .addComponent(creditcard3)
                            .addComponent(creditcard1)
                            .addComponent(creditcard4)
                            .addComponent(creditcard5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(creditcardBalance2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(creditcardLimit2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(creditcardBalance3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(creditcardLimit3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(creditcardBalance1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(creditcardLimit1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(creditcard6)
                                .addComponent(creditcard7)
                                .addComponent(creditcard8)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(164, 164, 164)
                                    .addComponent(creditcardBalance8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(creditcardLimit8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(enterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalUtilizationPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(creditcardBalance6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(41, 41, 41)
                                                .addComponent(creditcardLimit6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(creditcardBalance7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(41, 41, 41)
                                                .addComponent(creditcardLimit7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(totalUtilizationTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(creditcardBalance4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(creditcardLimit4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(creditcardBalance5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(creditcardLimit5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(creditUtilizationHeader, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(balanceTitle)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(limitTitle)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditUtilizationHeader)
                    .addComponent(dashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceTitle)
                    .addComponent(limitTitle))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditcard1)
                    .addComponent(creditcardBalance1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditcardLimit1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditcard2)
                    .addComponent(creditcardBalance2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditcardLimit2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditcard3)
                    .addComponent(creditcardBalance3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditcardLimit3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditcard4)
                    .addComponent(creditcardBalance4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditcardLimit4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditcard5)
                    .addComponent(creditcardBalance5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditcardLimit5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditcard6)
                    .addComponent(creditcardBalance6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditcardLimit6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditcard7)
                    .addComponent(creditcardBalance7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditcardLimit7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditcard8)
                    .addComponent(creditcardBalance8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditcardLimit8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalUtilizationTitle)
                        .addGap(18, 18, 18)
                        .addComponent(totalUtilizationPercentage)))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creditcardBalance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardBalance1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardBalance1ActionPerformed

    private void creditcardLimit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardLimit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardLimit1ActionPerformed

    private void creditcardBalance2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardBalance2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardBalance2ActionPerformed

    private void creditcardLimit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardLimit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardLimit2ActionPerformed

    private void creditcardBalance3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardBalance3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardBalance3ActionPerformed

    private void creditcardLimit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardLimit3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardLimit3ActionPerformed

    private void creditcardBalance4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardBalance4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardBalance4ActionPerformed

    private void creditcardLimit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardLimit4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardLimit4ActionPerformed

    private void creditcardLimit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardLimit5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardLimit5ActionPerformed

    private void creditcardBalance5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardBalance5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardBalance5ActionPerformed

    private void enterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterBtnActionPerformed
        double totalBalance = 0;
        double totalLimit = 0;
        int cardsFilled = 0;

// Arrays of credit card balance and limit fields
JTextField[] balanceFields = {
    creditcardBalance1, creditcardBalance2, creditcardBalance3, creditcardBalance4, creditcardBalance5, creditcardBalance6, creditcardBalance7, creditcardBalance8
};
JTextField[] limitFields = {
    creditcardLimit1, creditcardLimit2, creditcardLimit3, creditcardLimit4, creditcardLimit5, creditcardLimit6, creditcardLimit7, creditcardLimit8
};

for (int i = 0; i < balanceFields.length; i++) {
    String balanceText = balanceFields[i].getText().trim();
    String limitText = limitFields[i].getText().trim();

    if (!balanceText.isEmpty() && !limitText.isEmpty()) {
        try {
            double balance = Double.parseDouble(balanceText);
            double limit = Double.parseDouble(limitText);

            if (limit <= 0) {
                JOptionPane.showMessageDialog(this, "Credit card " + (i + 1) + " must have a limit greater than 0.");
                return;
            }

            totalBalance += balance;
            totalLimit += limit;
            cardsFilled++;

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid number in credit card " + (i + 1));
            return;
        }
    }
}
//Needs atleast one credit card balance and limit input to function
if (cardsFilled == 0) {
    JOptionPane.showMessageDialog(this, "Please fill in at least one credit card's balance and limit.");
    return;
}

double utilization = (totalBalance / totalLimit) * 100;
String utilizationText = String.format("%.2f", utilization);

// Display in the utilization field together with it's dedicated color
totalUtilizationPercentage.setText(utilizationText + "%");

if (utilization < 30) {
    totalUtilizationPercentage.setBackground(Color.GREEN);
} else if (utilization < 70) {
    totalUtilizationPercentage.setBackground(Color.YELLOW);
} else {
    totalUtilizationPercentage.setBackground(Color.RED);
}
    }//GEN-LAST:event_enterBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        JTextField[] allFields = {
        creditcardBalance1, creditcardBalance2, creditcardBalance3, creditcardBalance4,
        creditcardBalance5, creditcardBalance6, creditcardBalance7, creditcardBalance8,
        creditcardLimit1, creditcardLimit2, creditcardLimit3, creditcardLimit4,
        creditcardLimit5, creditcardLimit6, creditcardLimit7, creditcardLimit8,
        totalUtilizationPercentage
    };
    
    for (JTextField field : allFields) {
        field.setText("");
    }
    }//GEN-LAST:event_clearBtnActionPerformed

    private void creditcardBalance6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardBalance6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardBalance6ActionPerformed

    private void creditcardLimit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardLimit6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardLimit6ActionPerformed

    private void creditcardBalance7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardBalance7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardBalance7ActionPerformed

    private void creditcardLimit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardLimit7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardLimit7ActionPerformed

    private void creditcardBalance8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardBalance8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardBalance8ActionPerformed

    private void creditcardLimit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardLimit8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardLimit8ActionPerformed

    private void totalUtilizationPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalUtilizationPercentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalUtilizationPercentageActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditUtilization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditUtilization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditUtilization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditUtilization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreditUtilization().setVisible(true);
                
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balanceTitle;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel creditUtilizationHeader;
    private javax.swing.JLabel creditcard1;
    private javax.swing.JLabel creditcard2;
    private javax.swing.JLabel creditcard3;
    private javax.swing.JLabel creditcard4;
    private javax.swing.JLabel creditcard5;
    private javax.swing.JLabel creditcard6;
    private javax.swing.JLabel creditcard7;
    private javax.swing.JLabel creditcard8;
    private javax.swing.JTextField creditcardBalance1;
    private javax.swing.JTextField creditcardBalance2;
    private javax.swing.JTextField creditcardBalance3;
    private javax.swing.JTextField creditcardBalance4;
    private javax.swing.JTextField creditcardBalance5;
    private javax.swing.JTextField creditcardBalance6;
    private javax.swing.JTextField creditcardBalance7;
    private javax.swing.JTextField creditcardBalance8;
    private javax.swing.JTextField creditcardLimit1;
    private javax.swing.JTextField creditcardLimit2;
    private javax.swing.JTextField creditcardLimit3;
    private javax.swing.JTextField creditcardLimit4;
    private javax.swing.JTextField creditcardLimit5;
    private javax.swing.JTextField creditcardLimit6;
    private javax.swing.JTextField creditcardLimit7;
    private javax.swing.JTextField creditcardLimit8;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JButton enterBtn;
    private javax.swing.JLabel limitTitle;
    private javax.swing.JTextField totalUtilizationPercentage;
    private javax.swing.JLabel totalUtilizationTitle;
    // End of variables declaration//GEN-END:variables
}
