/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cs203_2.group2.kachingko.dashboard;
import cs203_2.group2.kachingko.dashboard.SpendingTrendline.SpendingTrendline;
import cs203_2.group2.kachingko.budget_planner.menu;
import cs203_2.group2.kachingko.auth.Session;
import cs203_2.group2.kachingko.monthlySpendingOverview.MonthlySpendingOverview;
import cs203_2.group2.kachingko.dashboard.CreditLimit.CreditUtilization;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import cs203_2.group2.kachingko.DBConnection;

public class DashboardFrame extends javax.swing.JFrame {

    public DashboardFrame() {
        initComponents();
        setSize(460, 680);
        setResizable(false);
        setLocationRelativeTo(null);
        
        displayCurrentUsername();
    }
    
    private void displayCurrentUsername() {
    try (Connection conn = DBConnection.getConnection()) {
        String query = "SELECT username FROM users WHERE id = ?";
        PreparedStatement stmt = conn.prepareStatement(query);
        stmt.setInt(1, Session.currentUserId); // gets currrent user id from database 
        //stmt.setInt(1, 1); //temporary id for testing
        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            String username = rs.getString("username");
            userLabel.setText(username);
        } else {
            userLabel.setText("User not found.");
        }

        rs.close();
        stmt.close();
    } catch (Exception e) {
        userLabel.setText("Error retrieving user.");
        e.printStackTrace();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameHeader = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        budgetPlannerBtn = new javax.swing.JButton();
        menuBtn = new javax.swing.JButton();
        monthlySpendingBtn = new javax.swing.JButton();
        spendingTrendlineBtn = new javax.swing.JButton();
        creditCardBtn = new javax.swing.JButton();
        dashboardBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        usernameHeader.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        usernameHeader.setForeground(new java.awt.Color(40, 87, 48));
        usernameHeader.setText("Welcome,");
        usernameHeader.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        usernameHeader.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(usernameHeader);
        usernameHeader.setBounds(60, 140, 72, 20);

        userLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        userLabel.setForeground(new java.awt.Color(96, 108, 56));
        userLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        userLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(userLabel);
        userLabel.setBounds(140, 140, 260, 19);

        budgetPlannerBtn.setBackground(new java.awt.Color(55, 74, 34));
        budgetPlannerBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        budgetPlannerBtn.setForeground(new java.awt.Color(242, 242, 242));
        budgetPlannerBtn.setText("<html>  BUDGET<br>PLANNER</html> ");
        budgetPlannerBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        budgetPlannerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetPlannerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(budgetPlannerBtn);
        budgetPlannerBtn.setBounds(230, 230, 170, 130);

        menuBtn.setBackground(new java.awt.Color(96, 108, 56));
        menuBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        menuBtn.setForeground(new java.awt.Color(242, 242, 242));
        menuBtn.setText("MENU");
        menuBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBtnActionPerformed(evt);
            }
        });
        getContentPane().add(menuBtn);
        menuBtn.setBounds(40, 540, 360, 60);

        monthlySpendingBtn.setBackground(new java.awt.Color(40, 54, 24));
        monthlySpendingBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        monthlySpendingBtn.setForeground(new java.awt.Color(242, 242, 242));
        monthlySpendingBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        monthlySpendingBtn.setLabel("<html>MONTHLY<br>SPENDING<br>OVERVIEW</html> ");
        monthlySpendingBtn.setMargin(new java.awt.Insets(2, 40, 3, 14));
        monthlySpendingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlySpendingBtnActionPerformed(evt);
            }
        });
        getContentPane().add(monthlySpendingBtn);
        monthlySpendingBtn.setBounds(40, 230, 170, 130);

        spendingTrendlineBtn.setBackground(new java.awt.Color(70, 94, 44));
        spendingTrendlineBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        spendingTrendlineBtn.setForeground(new java.awt.Color(242, 242, 242));
        spendingTrendlineBtn.setText("<html>SPENDING<br>TRENDLINE</html> ");
        spendingTrendlineBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        spendingTrendlineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spendingTrendlineBtnActionPerformed(evt);
            }
        });
        getContentPane().add(spendingTrendlineBtn);
        spendingTrendlineBtn.setBounds(40, 380, 170, 130);

        creditCardBtn.setBackground(new java.awt.Color(96, 108, 56));
        creditCardBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        creditCardBtn.setForeground(new java.awt.Color(242, 242, 242));
        creditCardBtn.setText("<html>CARD<br>UTILIZATION</html> ");
        creditCardBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        creditCardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditCardBtnActionPerformed(evt);
            }
        });
        getContentPane().add(creditCardBtn);
        creditCardBtn.setBounds(230, 380, 170, 130);

        dashboardBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboardBG.png"))); // NOI18N
        getContentPane().add(dashboardBG);
        dashboardBG.setBounds(0, -180, 460, 1020);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monthlySpendingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlySpendingBtnActionPerformed
            MonthlySpendingOverview spendingWindow = new MonthlySpendingOverview();
            spendingWindow.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_monthlySpendingBtnActionPerformed

    private void menuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBtnActionPerformed

    private void spendingTrendlineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spendingTrendlineBtnActionPerformed
            SpendingTrendline trendlineWindow = new SpendingTrendline();
            trendlineWindow.setVisible(true);
            
            this.setVisible(false);
    }//GEN-LAST:event_spendingTrendlineBtnActionPerformed

    private void budgetPlannerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgetPlannerBtnActionPerformed
        menu menuWindow = new menu();
        menuWindow.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_budgetPlannerBtnActionPerformed

    private void creditCardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditCardBtnActionPerformed
       CreditUtilization cardWindow = new CreditUtilization();
       cardWindow.setVisible(true);
       
       this.setVisible(false);
    }//GEN-LAST:event_creditCardBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton budgetPlannerBtn;
    private javax.swing.JButton creditCardBtn;
    private javax.swing.JLabel dashboardBG;
    private javax.swing.JButton menuBtn;
    private javax.swing.JButton monthlySpendingBtn;
    private javax.swing.JButton spendingTrendlineBtn;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel usernameHeader;
    // End of variables declaration//GEN-END:variables
}
