/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cs203_2.group2.kachingko.dashboard.Menu;

import cs203_2.group2.kachingko.DBConnection;
import javax.swing.*;
import java.awt.*;
import java.util.*;
import cs203_2.group2.kachingko.auth.Session;
/**
 *
 * @author ADMIN
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setTitle("Menu");
        setSize(460, 680);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alertRecommsBtn = new javax.swing.JButton();
        profileSettingsBtn = new javax.swing.JButton();
        dashboardBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(460, 680));
        setMinimumSize(new java.awt.Dimension(460, 680));
        setResizable(false);
        setSize(new java.awt.Dimension(460, 680));
        getContentPane().setLayout(null);

        alertRecommsBtn.setBackground(new java.awt.Color(55, 74, 34));
        alertRecommsBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        alertRecommsBtn.setForeground(new java.awt.Color(255, 255, 255));
        alertRecommsBtn.setText("ALERTS & RECOMMENDATIONS");
        alertRecommsBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        alertRecommsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertRecommsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(alertRecommsBtn);
        alertRecommsBtn.setBounds(90, 280, 280, 60);

        profileSettingsBtn.setBackground(new java.awt.Color(55, 74, 34));
        profileSettingsBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        profileSettingsBtn.setForeground(new java.awt.Color(255, 255, 255));
        profileSettingsBtn.setText("PROFILE & SETTINGS");
        profileSettingsBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        profileSettingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileSettingsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(profileSettingsBtn);
        profileSettingsBtn.setBounds(90, 350, 280, 60);

        dashboardBtn.setBackground(new java.awt.Color(96, 108, 56));
        dashboardBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        dashboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        dashboardBtn.setText("DASHBOARD");
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        getContentPane().add(dashboardBtn);
        dashboardBtn.setBounds(150, 590, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menuBG.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 460, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alertRecommsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertRecommsBtnActionPerformed
        // Open Alerts & Recommendations window
    try {
        cs203_2.group2.kachingko.dashboard.Menu.AlertsRecommendations.AlertsRecommendations alertsWindow = 
            new cs203_2.group2.kachingko.dashboard.Menu.AlertsRecommendations.AlertsRecommendations();
        alertsWindow.setVisible(true);
        this.dispose(); // Close current menu window
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error opening Alerts & Recommendations: " + e.getMessage(),
            "Navigation Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_alertRecommsBtnActionPerformed

    private void profileSettingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileSettingsBtnActionPerformed
        try {
        cs203_2.group2.kachingko.dashboard.Menu.ProfileSettings.ProfileSettings profileSettings = 
            new cs203_2.group2.kachingko.dashboard.Menu.ProfileSettings.ProfileSettings();
        profileSettings.setVisible(true);
        this.dispose(); // Close current menu window
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error opening Dashboard: " + e.getMessage(),
            "Navigation Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_profileSettingsBtnActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        try {
        cs203_2.group2.kachingko.dashboard.DashboardFrame dashboardWindow = 
            new cs203_2.group2.kachingko.dashboard.DashboardFrame();
        dashboardWindow.setVisible(true);
        this.dispose(); // Close current menu window
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error opening Dashboard: " + e.getMessage(),
            "Navigation Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_dashboardBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alertRecommsBtn;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton profileSettingsBtn;
    // End of variables declaration//GEN-END:variables
}
