/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cs203_2.group2.kachingko.dashboard.Menu;

import cs203_2.group2.kachingko.DBConnection;
import javax.swing.*;
import java.awt.*;
import java.util.*;
import cs203_2.group2.kachingko.auth.Session;
/**
 *
 * @author ADMIN
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setTitle("Menu");
        setSize(460, 655);
        setResizable(false);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuHeader = new javax.swing.JLabel();
        kachingkoHeader = new javax.swing.JLabel();
        alertRecommsBtn = new javax.swing.JButton();
        profileSettingsBtn = new javax.swing.JButton();
        dashboardBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(460, 680));
        setMinimumSize(new java.awt.Dimension(460, 680));
        setPreferredSize(new java.awt.Dimension(460, 680));
        setResizable(false);
        setSize(new java.awt.Dimension(460, 680));

        menuHeader.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        menuHeader.setText("Menu");

        kachingkoHeader.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        kachingkoHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kachingkoHeader.setText("Insert Kachingko!");

        alertRecommsBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        alertRecommsBtn.setText("Alerts & Recommendations");
        alertRecommsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertRecommsBtnActionPerformed(evt);
            }
        });

        profileSettingsBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        profileSettingsBtn.setText("Profile & Settings");
        profileSettingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileSettingsBtnActionPerformed(evt);
            }
        });

        dashboardBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        dashboardBtn.setText("Dashboard");
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kachingkoHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileSettingsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuHeader)
                    .addComponent(alertRecommsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(kachingkoHeader)
                .addGap(50, 50, 50)
                .addComponent(menuHeader)
                .addGap(106, 106, 106)
                .addComponent(alertRecommsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(profileSettingsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(dashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alertRecommsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertRecommsBtnActionPerformed
        // Open Alerts & Recommendations window
    try {
        cs203_2.group2.kachingko.dashboard.Menu.AlertsRecommendations.AlertsRecommendations alertsWindow = 
            new cs203_2.group2.kachingko.dashboard.Menu.AlertsRecommendations.AlertsRecommendations();
        alertsWindow.setVisible(true);
        this.dispose(); // Close current menu window
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error opening Alerts & Recommendations: " + e.getMessage(),
            "Navigation Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_alertRecommsBtnActionPerformed

    private void profileSettingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileSettingsBtnActionPerformed
        try {
        cs203_2.group2.kachingko.dashboard.Menu.ProfileSettings.ProfileSettings profileSettings = 
            new cs203_2.group2.kachingko.dashboard.Menu.ProfileSettings.ProfileSettings();
        profileSettings.setVisible(true);
        this.dispose(); // Close current menu window
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error opening Dashboard: " + e.getMessage(),
            "Navigation Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_profileSettingsBtnActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        try {
        cs203_2.group2.kachingko.dashboard.DashboardFrame dashboardWindow = 
            new cs203_2.group2.kachingko.dashboard.DashboardFrame();
        dashboardWindow.setVisible(true);
        this.dispose(); // Close current menu window
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error opening Dashboard: " + e.getMessage(),
            "Navigation Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_dashboardBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alertRecommsBtn;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JLabel kachingkoHeader;
    private javax.swing.JLabel menuHeader;
    private javax.swing.JButton profileSettingsBtn;
    // End of variables declaration//GEN-END:variables
}
